language: ruby
rvm:
- 2.4.5

notifications:
  email: false

bundler_args: --without development system_tests --path .vendor

script:
- bundle exec r10k puppetfile check
- bundle exec r10k puppetfile --verbose=info install

